#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail
IFS=$'\n\t'

fileList=$(mktemp)

ls -bv1Q /input/* > "${fileList}"

printf -- "Merging these files in this order:\n"
printf -- "%0.s-" {1..72}
echo

cat "${fileList}"

printf -- "%0.s-" {1..72}
echo

gs \
    -dNOPAUSE \
    -dBATCH \
    -sDEVICE=pdfwrite \
    -sOUTPUTFILE=/output/output.pdf \
    "@${fileList}"
