#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail
IFS=$'\n\t'

mapfile -t sortedFilenames < <(ls -bv1Q /input/*)

printf -- "Merging these files in this order:\n"
printf -- "%0.s-" {1..72}
echo
printf -- "%s\n" "${sortedFilenames[@]}"
printf -- "%0.s-" {1..72}
echo

gs \
-sDEVICE=pdfwrite \
-o "/output/output.pdf" \
"${sortedFilenames[@]}"
